language: php
php:
- 7.1
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.1
    env:
    - EXECUTE_DEPLOYMENT=true
before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
- composer info -i
script:
- echo "simple build"
before_deploy:
- tar xvf .travis/secrets.tar -C .travis
- eval "$(ssh-agent -s)"
- chmod 600 .travis/phar-private.pem
- ssh-add .travis/phar-private.pem
- git config --global user.email "opensource@iijaap.nl"
- git config --global user.name "jaapio"
- wget https://box-project.github.io/box2/manifest.json
- BOX_URL=$(php bin/parse-manifest.php manifest.json)
- rm manifest.json
- wget -O box.phar ${BOX_URL}
- php -d phar.readonly=false box.phar build
- openssl sha1 rolling-release.phar > rolling-releas.phar.sha1
deploy:
  provider: releases
  api_key:
    secure: jNlI5Fw6+Dp96GXivxmrQNjZnCfkZWT2fCvj/oIui6HIhlmn9WRpvrANYcb9P4DGvGwuF7k64rY1nOqgUT0xgSwZWOfFZPJzfs0PVG8gmTYTcvZIPBef/rmdo6W+mMzKCFT0PAVAUJlWaQ7OsOv9VhhEzq+K3KtpULNlL0RQFlLjdXQmztm+ns1eTBd95HG4m44h1pxcebknSqIFAjwfw4EAyIpDGfu4YMJEugzrM16qLLRvrbQy32Z8CIq9UP4ifdcr9H1Bsibm1hK3D4wrQX7knApCvjzeDYNyuoLgvHqpcKRPY3OKCDGZIdizUPUlexGBjsZGkp9Iu0CnfW7MYShMDYQmt9n0gco2ahNl310Zb+z8IAwAzflkVNu0CSam6SyvVX2A1rkslDrFeCaXJqYitMbC+HYCeZyzniUgPw4Jw0FoaYiBe0Sr88ZoiYeyZNteNOa5KP38JqMaV0PzK2ZJdmXIuLQLD69WXXSQKkhXGNY5HsFeeHHjJpZ4byrPlAPBKWreTsnOfDoO7dkLDuAykeETcm7QpNGHE34bNjkaruAphxsWJ63w12cQEeqyiNfoOcGmD9/sHMSDF/jTiMlIiBAnO0sCAQT8lGnUUbRFSIju0ONodvOD2gD4oIsnHNDdWwexP/kmylN6GQpxG5ZH/uygVRQN4HTw6UI5c7A=
  file:
    - "rolling-release.phar"
    - "rolling-release.phar.sha1"
  on:
    repo: jaapio/rolling-release
