language: php
php:
- 7.1
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.1
    env:
    - EXECUTE_DEPLOYMENT=true
before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
- composer info -i
script:
- echo "simple build"
before_deploy:
- tar xvf .travis/secrets.tar -C .travis
- eval "$(ssh-agent -s)"
- chmod 600 .travis/phar-private.pem
- ssh-add .travis/phar-private.pem
- git config --global user.email "opensource@iijaap.nl"
- git config --global user.name "jaapio"
- wget https://box-project.github.io/box2/manifest.json
- BOX_URL=$(php bin/parse-manifest.php manifest.json)
- rm manifest.json
- wget -O box.phar ${BOX_URL}
- php -d phar.readonly=false box.phar build
- openssl sha1 rolling-release.phar > rolling-releas.sha1
deploy:
  provider: releases
  api_key:
    secure: WUchZXQQdIDtVQTYZsQ++2R1y6I+EzBrAACRuc33wAVd0mlqNmu3nb/c1Ou4pTk5JxjyGqm9Siyp9vobhBtzBh/hdXAnbZDWNx2l6R1M9S4R/Z/VbcQ+uIJ/VOoh2KvIOCcyVuFVmsemlVQCuatCRKswKmK/OuyQXy6ppyZMilA=
  file:
  - rolling-release.phar
  - ''
  skip_cleanup: true
  on:
    repo: phpDocumentor/phpDocumentor2
    tags: true
    php: 7.1
